name = "tileserver"
usage_model = 'unbound'
main = "dist/worker.es.js"
compatibility_flags = []
compatibility_date = "2021-12-29"
account_id = "6b4ce0b3a6c21b7769cc1c3eff7eaadf"
workers_dev = true

[vars]
API_BASE_URL="https://dev.api.allmaps.org"
TILE_SERVER_BASE_URL="https://allmaps.xyz"

[build]
command="npm run build"
watch_dir="./src"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]
