name = "tileserver"
usage_model = 'unbound'
main = "dist/worker.es.js"
compatibility_flags = []
compatibility_date = "2021-12-29"
account_id = "514081276e13c9aa2894e2efde2dc41f"
workers_dev = true

[vars]
API_BASE_URL="https://api.allmaps.org"
TILE_SERVER_BASE_URL="https://allmaps.xyz"
TILES_VIEWER_BASE_URL="https://tiles.allmaps.org"

[build]
command="npm run build"
watch_dir="./src"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]
