packages:
  - 'packages/*'
  - 'apps/*'
  - 'workers/*'
  - 'test/*'

catalog:
  '@types/node': ^24

  'vitest': ^4.0.5
  'typescript': ^5.9.2

  'eslint': ^9.36.0
  'eslint-config-prettier': ^9.1.0
  'prettier': ^3.6.2
  'typescript-eslint': ^8.44.1

  'zod': ^3.22.4
  'tailwindcss': ^4.1.13
  'svelte': ^5.43.2
  'svelte-check': ^4.3.2
  '@sveltejs/kit': ^2.47.1
  '@sveltejs/vite-plugin-svelte': ^6.2.0

  'wrangler': ^4.3.0
