name = "preview"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[vars]
USE_CACHE=true
API_BASE_URL="https://api.allmaps.org"

[env.dev.vars]
USE_CACHE=false
API_BASE_URL="https://api.allmaps.org"
