name = "preview"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[vars]
API_BASE_URL="https://api.allmaps.org"
TILE_SERVER_BASE_URL="https://allmaps.xyz"
TILE_VIEWER_BASE_URL="https://tiles.allmaps.org"
