import { PUBLIC_EXPERIMENTAL_FEATURES } from '$env/static/public'

export default PUBLIC_EXPERIMENTAL_FEATURES === 'true' ||
  PUBLIC_EXPERIMENTAL_FEATURES === 'TRUE' ||
  PUBLIC_EXPERIMENTAL_FEATURES === 'True' ||
  PUBLIC_EXPERIMENTAL_FEATURES === '1'
