name = "here"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-01-01"

site = {  bucket = "./.cloudflare/public" }
build = { command = "pnpm install --no-frozen-lockfile && pnpm run lerna-build" }
assets = { directory = "public",  binding = "ASSETS" }

[vars]
USE_CACHE=true
API_BASE_URL="https://api.allmaps.org"

[env.dev]
name = "here-next"

[env.dev.vars]
USE_CACHE=false
API_BASE_URL="https://api.allmaps.org"
