name = "here"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-01-01"

assets = { directory = ".svelte-kit/cloudflare",  binding = "ASSETS" }
#observability = { enabled = "true" }

[env.dev]
name = "here-next"

[vars]
PUBLIC_ANNOTATIONS_URL = "https://annotations.allmaps.org"
PUBLIC_PREVIEW_URL= "https://next.preview.allmaps.org/apps/here"

[env.dev.vars]
PUBLIC_ANNOTATIONS_URL = "https://annotations.allmaps.org"
PUBLIC_PREVIEW_URL = "http://localhost:5514/apps/here"
