export type Env = {
  PUBLIC_ALLMAPS_API_WS_URL: string
  PUBLIC_ALLMAPS_API_URL: string
  PUBLIC_ALLMAPS_ANNOTATIONS_API_URL: string
  PUBLIC_ALLMAPS_PREVIEW_URL: string
  PUBLIC_ALLMAPS_VIEWER_URL: string
  PUBLIC_ALLMAPS_TILE_SERVER_URL: string
  PUBLIC_EXAMPLES_API_URL: string
  PUBLIC_STATS_WEBSITE_ID?: string
  VITE_BANNER_ENABLED?: boolean
  VITE_BANNER_TEXT?: string
  PUBLIC_GEOCODE_EARTH_KEY?: string
}
