export const ALLMAPS_THEME = {
  background: '#cccccc',
  earth: '#e0e0e0',
  park_a: '#cfddd5',
  park_b: '#9cd3b4',
  hospital: '#e4dad9',
  industrial: '#d1dde1',
  school: '#e4ded7',
  wood_a: '#d0ded0',
  wood_b: '#a0d9a0',
  pedestrian: '#e3e0d4',
  scrub_a: '#cedcd7',
  scrub_b: '#99d2bb',
  glacier: '#e7e7e7',
  sand: '#e2e0d7',
  beach: '#e8e4d0',
  aerodrome: '#dadbdf',
  runway: '#e9e9ed',
  water: '#dff7fa',
  pier: '#e0e0e0',
  zoo: '#c6dcdc',
  military: '#dcdcdc',

  tunnel_other_casing: '#e0e0e0',
  tunnel_minor_casing: '#e0e0e0',
  tunnel_link_casing: '#e0e0e0',
  tunnel_medium_casing: '#e0e0e0',
  tunnel_major_casing: '#e0e0e0',
  tunnel_highway_casing: '#e0e0e0',
  tunnel_other: '#d5d5d5',
  tunnel_minor: '#d5d5d5',
  tunnel_link: '#d5d5d5',
  tunnel_medium: '#d5d5d5',
  tunnel_major: '#d5d5d5',
  tunnel_highway: '#d5d5d5',

  transit_pier: '#e0e0e0',
  buildings: '#cccccc',

  minor_service_casing: '#e0e0e0',
  minor_casing: '#e0e0e0',
  link_casing: '#e0e0e0',
  medium_casing: '#e0e0e0',
  major_casing_late: '#e0e0e0',
  highway_casing_late: '#e0e0e0',
  other: '#ebebeb',
  minor_service: '#ebebeb',
  minor_a: '#ebebeb',
  minor_b: '#ffffff',
  link: '#ffffff',
  medium: '#f5f5f5',
  major_casing_early: '#e0e0e0',
  major: '#ffffff',
  highway_casing_early: '#e0e0e0',
  highway: '#ffffff',

  railway: '#a7b1b3',
  boundaries: '#adadad',
  waterway_label: '#ffffff',

  bridges_other_casing: '#e0e0e0',
  bridges_minor_casing: '#e0e0e0',
  bridges_link_casing: '#e0e0e0',
  bridges_medium_casing: '#e0e0e0',
  bridges_major_casing: '#e0e0e0',
  bridges_highway_casing: '#e0e0e0',
  bridges_other: '#ebebeb',
  bridges_minor: '#ffffff',
  bridges_link: '#ffffff',
  bridges_medium: '#f0eded',
  bridges_major: '#f5f5f5',
  bridges_highway: '#ffffff',

  roads_label_minor: '#91888b',
  roads_label_minor_halo: '#ffffff',
  roads_label_major: '#938a8d',
  roads_label_major_halo: '#ffffff',
  ocean_label: '#ffffff',
  peak_label: '#7e9aa0',
  subplace_label: '#8f8f8f',
  subplace_label_halo: '#e0e0e0',
  city_label: '#5c5c5c',
  city_label_halo: '#e0e0e0',
  state_label: '#b3b3b3',
  state_label_halo: '#e0e0e0',
  country_label: '#a3a3a3'
}

export const TERRAIN_THEME = {
  hillshade_shadow_color: '#bbb',
  hillshade_accent_color: 'blue',
  hillshade_highlight_color: 'white',
  contour_line_color: 'purple'
}
