name = "preview"
main = "src/index.ts"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat_v2"]

assets = { directory = "public",  binding = "ASSETS" }

[vars]
USE_CACHE=true
API_BASE_URL="https://api.allmaps.org"

[env.dev.vars]
USE_CACHE=false
API_BASE_URL="https://api.allmaps.org"
