name = "tileserver"
main = "src/index.ts"
compatibility_date = "2024-05-24"
compatibility_flags = ["nodejs_compat"]

[vars]
USE_CACHE=true
API_BASE_URL="https://api.allmaps.org"
TILE_SERVER_BASE_URL="https://allmaps.xyz"
TILE_VIEWER_BASE_URL="https://tiles.allmaps.org"

[env.dev.vars]
USE_CACHE=false
API_BASE_URL="https://api.allmaps.org"
TILE_SERVER_BASE_URL="http://localhost:5504"
TILE_VIEWER_BASE_URL="https://tiles.allmaps.org"

